version: "3.8"

services:

    encoder:
        container_name: encoder
        build: .
        environment:
            - ENCODER_CPU=false
            - EXIT_ON_FINISH=true
            - WORKER_ID=dev
        volumes:
            - "./data-local:/media/encoder"
        devices:
            - "/dev/dri/renderD128"
