version: "3.8"

services:

    encoder:
        container_name: encoder
        build: .
        environment:
            - CREATE_FOLDERS=true
            - ENCODER_CPU=true
            - EXIT_ON_FINISH=true
            - SERVER_IDENTITY=
            - |
                SERVER_KEY=
            # - SERVER_URL=sftp://sftp@sftp-server:22
            - WORKER_ID=dev
        volumes:
            - "./data-local/data:/media/encoder"
        devices:
            - "/dev/dri/renderD128"

    # sftp-server:
    #     container_name: sftp-server
    #     image: madebytimo/sftp-server
    #     volumes:
    #         - ./data-local/ssh/ssh-key.pub:/media/ssh/authorized_keys:ro
    #         - ./data-local/ssh/ssh-key:/media/ssh/host_key:ro
    #         - ./data-local/data:/media/sftp/data
    #     ports:
    #         - "127.0.0.1:8022:22"
