name: "Check version increment"

on:
    pull_request:
        branches:
            - main

jobs:
    check:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout new
              uses: actions/checkout@v4
              with:
                  path: new
            - name: Checkout old
              uses: actions/checkout@v4
              with:
                  path: old
                  ref: refs/heads/main
            - name: Setup Node.js
              uses: actions/setup-node@v4
            - name: Download script
              run: |
                  curl --silent --output check-version-increment.sh \
                      https://gitlab.com/madebyTimo/scripts-development/-/raw/main/scripts/\
                  check-version-increment.sh \
                      && chmod +x check-version-increment.sh
            - name: Test version increment
              run: |
                  BRANCH="${GITHUB_HEAD_REF#/ref/head}"
                  echo "Branch to check: $BRANCH"
                  if [[ "$BRANCH" == @(feature|bugfix)/* ]]; then
                      ./check-version-increment.sh --file --new new/Version.txt \
                          --old old/Version.txt
                  else
                      [[ $(cat new/Version.txt) == $(cat old/Version.txt) ]]
                  fi
